- name: NGINX is working and installed properly
  apt: 
    name: nginx  
    
- name: prometheus-nginx-exporter
  ansible.builtin.apt:
    name: prometheus-nginx-exporter
    state: latest
    
- name: source default to destionation sites/enabled
  template:
    src: exporter
    dest: /etc/nginx/sites-enabled/exporter
  notify: restart nginx exporter
  
- name: source default to destionation sites/enabled
  template:
    src: default.j2
    dest: /etc/nginx/sites-enabled/default
  notify: restart nginx
  
- name: Enable exporter service
  service:
   name: prometheus-nginx-exporter
   state: started
   enabled: yes

- name: start nginx service
  service:
    name: nginx
    state: started 
    enabled: yes
