- name: Install nginx
  apt:
    name: nginx
    state: present

- name: Copy default to Sites-enabled
  ansible.builtin.template:
    src: default.j2
    dest: /etc/nginx/sites-enabled/default
  notify: restart nginx
  no_log: true

- name: Ensure Nginx service is started and enabled at boot
  ansible.builtin.service:
    name: nginx
    state: started
    enabled: true

- name: Install Nginx exporter
  apt:
    name: prometheus-nginx-exporter
    state: present
  become: yes

- name: Start and enable nginx exporter
  ansible.builtin.service:
    name: prometheus-nginx-exporter
    state: started
    enabled: yes
  become: yes

- name: Upload prometheus-nginx-exporter configuration
  ansible.builtin.template:
    src: prometheus-nginx-exporter 
    dest: /etc/default/prometheus-nginx-exporter 
  notify: restart prometheus-nginx-exporter 
  no_log: yes

- name: Add www CNAME records
  community.general.nsupdate:
    key_name: "nsupdate.key"
    key_algorithm: "hmac-sha256"
    key_secret: "{{ dns_nsupdate_key }}"
    server: "localhost"
    zone: "{{ fqdn }}"
    record: "{{ item.key }}"
    type: "CNAME"
    value: "{{ item.value }}"
  loop: "{{ dns_nginx_records | dict2items }}"
  delegate_to: "{{ groups['dns_primary'][0] }}"
  
