- name: Install HAProxy
  ansible.builtin.apt:
    name: haproxy
    state: present
    update_cache: yes

- name: Upload HAProxy configuration
  ansible.builtin.template:
    src: haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.cfg
  notify: restart haproxy
  no_log: true

- name: Ensure HAProxy is running and enabled
  ansible.builtin.service:
    name: haproxy
    state: started
    enabled: yes

- name: Install HAproxy exporter
  ansible.builtin.apt:
    name: prometheus-haproxy-exporter

- name: Upload HAproxy exporter configuration
  ansible.builtin.template:
    src: prometheus-haproxy-exporter.j2
    dest: /etc/default/prometheus-haproxy-exporter
  notify: restart prometheus-haproxy-exporter
  no_log: true
      
- name: Ensure HAproxy exporter is started
  ansible.builtin.service:
    name: prometheus-haproxy-exporter
    enabled: yes
    state: started

- name: Add HAproxy CNAME records
  community.general.nsupdate:
    key_name: "nsupdate.key"
    key_algorithm: "hmac-sha256"
    key_secret: "{{ dns_nsupdate_key }}"
    server: "localhost"
    zone: "{{ fqdn }}"
    record: "{{ item.key }}"
    type: "CNAME"
    value: "{{ item.value }}"
  loop: "{{ dns_haproxy_records | dict2items }}"
  delegate_to: "{{ groups['dns_primary'][0] }}"
