- name: Install HAProxy
  ansible.builtin.apt:
    name: haproxy
    state: present
    update_cache: yes

- name: Upload HAProxy configuration
  ansible.builtin.template:
    src: haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.cfg
  notify: restart haproxy
  no_log: true

- name: Ensure HAProxy is running and enabled
  ansible.builtin.service:
    name: haproxy
    state: started
    enabled: yes

- name: Install HAproxy exporter
  ansible.builtin.apt:
    name: prometheus-haproxy-exporter

- name: Upload HAproxy exporter configuration
  ansible.builtin.template:
    src: prometheus-haproxy-exporter.j2
    dest: /etc/default/prometheus-haproxy-exporter
  notify: restart prometheus-haproxy-exporter
  no_log: true
      
- name: Ensure HAproxy exporter is started
  ansible.builtin.service:
    name: prometheus-haproxy-exporter
    enabled: yes
    state: started
