---
- name: Dependencies for Grafana
  ansible.builtin.apt:
     name:
         - adduser
         - libfontconfig1

- name: Add Grafana Apt signing key
  ansible.builtin.apt_key:
    url: https://packages.grafana.com/gpg.key
    state: present
        
- name: Download Grafana
  ansible.builtin.get_url:
    url: https://dl.grafana.com/oss/release/grafana_7.2.1_amd64.deb
    dest: /opt/grafana_7.2.1_amd64.deb 
    
- name: Install Grafana
  ansible.builtin.apt:
    deb: /opt/grafana_7.2.1_amd64.deb
        
- name: Upload grafana ini configuration
  ansible.builtin.template:
    src: grafana.ini.j2
    dest: /etc/grafana/grafana.ini
  notify: restart grafana
  no_log: yes

- name: Ensure grafana is always started please
  ansible.builtin.service:
    name: grafana-server
    enabled: yes
    state: started
      
- name: Upload grafana prometheus data source
  ansible.builtin.template:
    src: datasources.yaml
    dest: /etc/grafana/provisioning/datasources/datasources.yaml
  notify: restart grafana
   
- name: Create dashboard path
  file:
    path: /var/lib/grafana/dashboards.yaml
    state: directory  
  
- name: Copy file main dashboard
  ansible.builtin.copy:
    src: main.json
    dest: /var/lib/grafana/dashboards/
  notify: restart grafana
  
- name: Upload grafana dashboard config
  ansible.builtin.template:
    src: dashboards.yaml
    dest: /etc/grafana/provisioning/dashboards/dashboards.yaml
  notify: restart grafana
