- name: Provisioning config - Create directories
  file:  
    path: "/opt/grafana/provisioning/{{ item.directory }}"
    state: directory
  loop:
    - { directory: 'dashboards' }
    - { directory: 'datasources' }

- name: Template grafana.ini
  template:
    dest: /opt/grafana/grafana.ini
    src: grafana.ini.j2
    mode: '0644'
  notify: restart grafana

- name: Template files
  template:
    dest: "/opt/grafana/provisioning/{{ item.directory }}/{{ item.file }}"
    src: "{{ item.srcfile }}"
    mode: '0644'
  loop:
    - { directory: 'dashboards', file: 'default.yaml', srcfile: 'dashboards.yaml.j2' }
    - { directory: 'datasources', file: 'default.yaml', srcfile: 'datasources.yaml' }
  notify: restart grafana


- name: Copy files
  copy:
    dest: "/opt/grafana/provisioning/dashboards/{{ item }}"
    src: "{{ item }}"
  loop:
    - main.json 
    - mysql.json
    - syslog.json
  notify: restart grafana

- name: Start Grafana in docker container
  community.docker.docker_container:
    name: grafana
    image: grafana/grafana
    volumes: /opt/grafana:/etc/grafana
    ports: "{{ grafana_port }}:3000"
    state: started
    restart_policy: "always"

    
