- name: needed uwsgi packages
  apt:
    pkg:
    - uwsgi
    - uwsgi-plugin-python3
    - python3-pymysql

- name: copying file to server
  template:
    src: agama.ini.j2
    dest: /etc/uwsgi/apps-enabled/agama.ini
    owner: agama
    mode: 0600
  notify: restart uwsgi

- name: changing resolv conf for vm1
  template:
    src: resolv.conf
    dest: /etc/resolv.conf

- name: start uwsgi service
  service:
    name: uwsgi
    state: started
    enabled: yes
