- name: Initial setup
  hosts: all
  tags:
    - init
  roles:
    - init

- name: Database server
  hosts: db_servers
  tags:
    - db
    - sql
    - mysql
  roles:
    - mysql

- name: DNS setup
  hosts: all
  roles:
    - dns_setup
  tags:
    - dns
    
- name: docker
  hosts: all
  roles:
    - docker
  tags:
    - docker

- name: Agama
  hosts: agama
  roles:
    - agama
  tags:
    - agama

- name: Deploy Web Servers
  hosts: web_servers
  tags:
    - web
    - nginx
  roles:
    - agama
    # - uwsgi
    - nginx

- name: DNS Server Setup
  hosts: dns_servers
  become: yes
  gather_facts: yes
  tags:
    - dns
    - bind
    - bind9
  roles:
    - bind

- name: Prometheus server
  hosts: prometheus
  tags:
    - monitoring
    - prom
    - prometheus
  roles:
    - prometheus
    - nginx
    - grafana

- name: InfluxDB server
  hosts: influxdb
  tags:
    - influxdb
    - telegraf
  roles:
    - influxdb
    - pinger
    
- name: Keepalived and Haproxy
  hosts: haproxy
  roles:
    - keepalived
    - haproxy
  tags:
    - ha  
