{
 "title": "Main",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "Nginx UP/DOWN state",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "nginx_up", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "SQL",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 5, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "mysql_up" }
   ]
  },
  {
   "title": "HTTP request",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 10, "y": 0 },
   "targets": [
    {
     "expr": "(increase(nginx_http_requests_total [1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "DNS queries",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 0 },
   "targets": [
    {
     "expr": "sum(increase(bind_resolver_queries_total [1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "SQL selects",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 0 },
   "targets": [
    {
     "expr": "sum(increase(mysql_global_status_commands_total [1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "keepalive master/backup status",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "keepalived_vrrp_state", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "bind status",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 5, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "bind_up", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "CPU LOAD on VMS",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 10, "y": 6 },
   "targets": [
    {
     "expr": "100-(1-rate(node_cpu_seconds_total{mode=\"idle\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average CPU",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 6 },
   "targets": [
    {
     "expr": "(1 - avg(irate(node_cpu_seconds_total{mode=\"idle\"}[5m])) by (instance)) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Haproxy up",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "haproxy_up", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Haproxy server up",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 5, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "haproxy_server_up", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "InfluxDb health",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "influxdb_exporter_stats_query_success",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory consumption on VMs",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 10, "x": 14, "y": 12 },
   "targets": [
    {
     "expr": " (node_memory_Buffers_bytes + node_memory_Cached_bytes + node_memory_MemFree_bytes) / node_memory_MemTotal_bytes * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "MYSQL status rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 13 },
   "targets": [
    {
     "expr": "mysql_global_status_commands_total",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average Memory Consumption",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 8, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "100 * (1 - ((node_memory_MemFree_bytes + node_memory_Cached_bytes + node_memory_Buffers_bytes) / node_memory_MemTotal_bytes))\n"
    }
   ]
  },
  {
   "title": "Influxdb Write rate",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 10, "x": 14, "y": 16 },
   "targets": [
    {
     "expr": "rate(influxdb_write_write_ok[1m])",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}