{
 "title": "MySQL",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "MySQL status",
   "type": "stat",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "mysql_up", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "MySQL Server IDs",
   "type": "stat",
   "gridPos": { "h": 4, "w": 7, "x": 7, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mysql_global_variables_server_id",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Slave SQL Running",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 7, "x": 14, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mysql_slave_status_slave_sql_running{master_uuid=\"51fec2f0-9f0b-11ee-b974-fa163e433ddc\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Avg Queries",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 7, "x": 7, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by(instance) (mysql_global_status_commands_total)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "MySQL Replication Threads",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 7, "x": 14, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mysql_slave_status_slave_io_running{master_uuid=\"51fec2f0-9f0b-11ee-b974-fa163e433ddc\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Read-Only status",
   "type": "stat",
   "gridPos": { "h": 5, "w": 7, "x": 0, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mysql_global_variables_read_only",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}