---

  - name: Restart bind
    ansible.builtin.service:
      name: bind9
      state: restarted
      enabled: yes
      
  - name: Reload rndc
    shell: rndc reload
    
  - name: restart prometheus-bind-exporter
    ansible.builtin.service:
      name: prometheus-bind-exporter
      state: restarted
