apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:{{ prometheus_port }}/prometheus
    isDefault: True
    uid: prometheus

  - name: InfluxDB-Latency
    type: influxdb
    access: proxy
    url: http://influxdb:{{ influxdb_port }}
    isDefault: False
    database: latency
    uid: latency

  - name: InfluxDB-Telegraf
    type: influxdb
    access: proxy
    url: http://influxdb:{{ influxdb_port }}
    isDefault: False
    database: telegraf
    uid: telegraf
