# config file version
apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    orgId: 1
    uid: prometheus1
    url: http://{{ groups['prometheus'][0] }}:{{ prometheus_port }}/prometheus
    version: 1
    editable: false
  
