- name: Install Prometheus
  apt:
    name: prometheus

- name: Prometheus args
  template:
    src: prometheus.j2
    dest: /etc/default/prometheus
  notify:
    - Restart Prometheus
    
- name: Change prometheus.yml
  template:
    src: prometheus.yml.j2
    dest: /etc/prometheus/prometheus.yml
  notify: Restart Prometheus    

- name: Enable Prometheus
  service:
    name: prometheus
    state: started
    enabled: yes

- name: Add Prometheus CNAME records
  community.general.nsupdate:
    key_name: "nsupdate.key"
    key_algorithm: "hmac-sha256"
    key_secret: "{{ dns_nsupdate_key }}"
    server: "localhost"
    zone: "{{ fqdn }}"
    record: "{{ item.key }}"
    type: "CNAME"
    value: "{{ item.value }}"
  loop: "{{ dns_prometheus_records | dict2items }}"
  delegate_to: "{{ groups['dns_primary'][0] }}"
  
