#- name: Ansible ping module
#  ansible.builtin.ping:
- name: Update APT cache
  ansible.builtin.apt:
    cache_valid_time: 86400

- name: Exporter packages
  apt:
    name: 
      - prometheus-node-exporter
      - nginx
