
- name: Update APT cache
  ansible.builtin.apt:
    cache_valid_time: 86400

- name: Install Prometheus node_exporter
  apt:
    name: prometheus-node-exporter
    state: present

- name: Start node exporter
  ansible.builtin.service:
    name: prometheus-node-exporter
    state: started
    enabled: yes
  become: yes

- name: Ensure up-to-date CA certificates are installed
  apt:
    name: ca-certificates=20230311ubuntu0.20.04.1
    state: present

- name: Copy rsyslog config
  ansible.builtin.template:
    src: telegraf.conf.j2
    dest: /etc/rsyslog.d/telegraf.conf
  notify:
    - Restart rsyslog

- name: Add the user 'backup'
  ansible.builtin.user:
    name: backup
    comment: backup
    shell: /bin/bash
    home: /home/backup
    generate_ssh_key: yes
    
- name: Template a file to /home/backup/.ssh/known_hosts
  ansible.builtin.template:
    src: known_hosts
    dest: /home/backup/.ssh/known_hosts
    owner: backup
    group: backup
    mode: 0644

- name: Ensure restoration directory exists
  ansible.builtin.file:
    path: /home/backup/restore
    state: directory
    owner: backup
    group: backup
    mode: '0750'
  become: yes

- name: Install Duplicity
  apt:
    name: duplicity
    state: present
  become: yes

#- name: Update resolv.conf
#  ansible.builtin.template:
#    src: resolv.conf.j2
#    dest: /etc/resolv.conf
#  when: "'dns_servers' not in group_names"
